version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge